In [85]:
%load_ext autoreload
%autoreload 2

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

from pytorch_models_imp.detectors.utils import intersection_over_union

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [86]:
t1_box1 = torch.tensor([[1, 2, 3, 4], [1, 1, 3, 3]])
t1_box2 = torch.tensor([[2, 0, 4, 2], [1, 2, 3, 4]])

In [95]:
intersection_over_union(t1_box1, t1_box2).flatten()

tensor([0.0000, 0.3333])

In [55]:
1 / 7

0.14285714285714285

In [5]:
x_min_pred = t1_box1[:, 0].unsqueeze(0)
y_min_pred = t1_box1[:, 1].unsqueeze(0)
x_max_pred = t1_box1[:, 2].unsqueeze(0)
y_max_pred = t1_box1[:, 3].unsqueeze(0)

x_min_true = t1_box2[:, 0].unsqueeze(0)
y_min_true = t1_box2[:, 1].unsqueeze(0)
x_max_true = t1_box2[:, 2].unsqueeze(0)
y_max_true = t1_box2[:, 3].unsqueeze(0)

In [6]:
torch.max(x_min_pred, x_min_true)

tensor([[0.9000]])

In [7]:
x_min_pred

tensor([[0.8000]])

In [36]:
1 / 4

0.25